### ISSUE TITLE
Constants for rsbeams and rslasers

### ISSUE THREAD

**Issue by gurhar1133** [radiasoft/rsmath#1]
Previously these constants were going to live in pykern. The goal is to consolidate use of command constants and mathematical functionality from rsbeams, rslasers etc. into this repo (see this issue [#55](https://github.com/radiasoft/rslaser/issues/55) ).

Currently constants live in [/rsmath/constants/constants.py](https://github.com/radiasoft/rsmath/blob/master/rsmath/constants/constants.py)

We can use this issue to communicate about the changes needed for constants @bruhwiler and @robnagler

**Comment by bruhwiler** [comment]
I suggest we use pykern as a model and forget about creating subdirectories within rsmath/rsmath
In other words, move constants.py up one level and delete the constants/ subdirectory.

**Comment by robnagler** [comment]
Agreed. You could also call it `const.py` since that's a pretty well known abbreviation.

**Comment by gurhar1133** [comment]
Sounds good to me

**Comment by gurhar1133** [comment]
Moved rsmath/constants/constants.py to rsmath/const.py. Any think need to be done with the contents of the file? LMK

**Comment by bruhwiler** [comment]
File contents look good to me.
