### ISSUE TITLE
Include Linear Canonical Transform

### ISSUE THREAD

**Issue by gurhar1133** [radiasoft/rsmath#4]
* in rsmath/rsmath we should create a module for linear canonical transforms
* The set of functions for doing so defined by @dtabell can be converted into class structure as well

**Comment by dtabell** [comment]
The notebook [FastLCT.ipynb](https://github.com/radiasoft/rslight/blob/main/LCT/FastLCT.ipynb) contains all functions and tests needed to get started with this task.
For now, the functions to extract are the following:
* `lct_abscissae`
* `resample_signal`
* `scale_signal`
* `lct_fourier`
* `chirp_multiply`
* `lct_decomposition`
* `apply_lct`

The above notebook also implements a series of tests that can be converted to unit tests.
I am happy to discuss further—either here or in person.

Some details remain for Boaz and I to iron out, but those affect primarily some processing of the signal on input and output. We anticipate those details requiring at most minor adjustments to the above functions as presently implemented.

**Comment by dtabell** [comment]
I don't see how to assign this task to anyone—to me or to someone else.

**Comment by bruhwiler** [comment]
@dtabell -- try again. I just changed the settings so that all RadiaSoft staff have write access to this repo.

**Comment by bruhwiler** [comment]
@gurhar1133 -- is this on your todo list?

**Comment by gurhar1133** [comment]
> @gurhar1133 -- is this on your todo list?

I can bump it up in priority 👍
